# Generated by Django 2.0.6 on 2018-07-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, default='', max_length=128)),
                ('eventid', models.CharField(blank=True, default='', max_length=20)),
                ('zabbix_id', models.IntegerField()),
                ('device_type', models.CharField(blank=True, default='', max_length=32)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('ip', models.CharField(max_length=20)),
                ('message', models.TextField(null=True)),
                ('oc_time', models.IntegerField()),
                ('ack_time', models.IntegerField(null=True)),
                ('sendto', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.IntegerField(null=True)),
                ('desc', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
            options={
                'db_table': 'alert',
            },
        ),
        migrations.CreateModel(
            name='AlertHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(blank=True, default='', max_length=20)),
                ('zabbix_id', models.IntegerField()),
                ('device_type', models.CharField(blank=True, default='', max_length=32)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('ip', models.CharField(max_length=20)),
                ('item', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField()),
                ('oc_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('ack_time', models.IntegerField(null=True)),
                ('sendto', models.CharField(max_length=64)),
                ('status', models.IntegerField(null=True)),
                ('deal_person', models.CharField(blank=True, default='', max_length=64)),
                ('deal_details', models.TextField(null=True)),
                ('deal_end_time', models.IntegerField(null=True)),
                ('desc', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
            options={
                'db_table': 'alert_his',
            },
        ),
        migrations.CreateModel(
            name='AlertLev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('desc', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
            options={
                'db_table': 'alert_lev',
            },
        ),
        migrations.CreateModel(
            name='CloudDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('ip', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('agent', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'db_table': 'cloud_device',
            },
        ),
        migrations.CreateModel(
            name='CloudDeviceToZabbix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('host_ip', models.CharField(blank=True, default='', max_length=64)),
                ('app_name', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.CharField(blank=True, default='', max_length=64)),
                ('park', models.CharField(blank=True, default='', max_length=64)),
                ('room', models.CharField(blank=True, default='', max_length=64)),
                ('rock', models.CharField(blank=True, default='', max_length=64)),
                ('U_start', models.CharField(blank=True, default='', max_length=64)),
                ('U_stop', models.CharField(blank=True, default='', max_length=64)),
                ('data_center', models.CharField(blank=True, default='', max_length=64)),
                ('vendors', models.CharField(blank=True, default='', max_length=128)),
                ('cluster', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'cloud_cevice_2_zabbix',
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('group_id', models.CharField(max_length=8)),
                ('zabbix_id', models.IntegerField(null=True)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'db_table': 'device_group',
            },
        ),
        migrations.CreateModel(
            name='DeviceLev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
            options={
                'db_table': 'device_lev',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('desc', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
            options={
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
            options={
                'db_table': 'fault',
            },
        ),
        migrations.CreateModel(
            name='Fw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('status', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fws', to='dashBoard.DeviceGroup')),
            ],
            options={
                'db_table': 'fw',
            },
        ),
        migrations.CreateModel(
            name='Fz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('status', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fzs', to='dashBoard.DeviceGroup')),
            ],
            options={
                'db_table': 'fz',
            },
        ),
        migrations.CreateModel(
            name='MTInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('oc_time', models.IntegerField(null=True)),
                ('end_time', models.IntegerField(null=True)),
                ('hostid', models.IntegerField(null=True)),
                ('maintenanceid', models.IntegerField(null=True)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mt_informations', to='dashBoard.DeviceGroup')),
            ],
            options={
                'db_table': 'mtinformation',
            },
        ),
        migrations.CreateModel(
            name='NetworkDeviceToZabbix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('host_ip', models.CharField(blank=True, default='', max_length=64)),
                ('app_name', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.CharField(blank=True, default='', max_length=64)),
                ('park', models.CharField(blank=True, default='', max_length=64)),
                ('room', models.CharField(blank=True, default='', max_length=64)),
                ('rock', models.CharField(blank=True, default='', max_length=64)),
                ('U_start', models.CharField(blank=True, default='', max_length=64)),
                ('U_stop', models.CharField(blank=True, default='', max_length=64)),
                ('data_center', models.CharField(blank=True, default='', max_length=64)),
                ('vendors', models.CharField(blank=True, default='', max_length=128)),
                ('device_type', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'network_nevice_2_zabbix',
            },
        ),
        migrations.CreateModel(
            name='ResourceHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('ip', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('agent', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_hosts', to='dashBoard.DeviceGroup')),
            ],
            options={
                'db_table': 'resource_host',
            },
        ),
        migrations.CreateModel(
            name='ResourceHostToZabbix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('host_ip', models.CharField(blank=True, default='', max_length=64)),
                ('app_name', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.CharField(blank=True, default='', max_length=64)),
                ('park', models.CharField(blank=True, default='', max_length=64)),
                ('room', models.CharField(blank=True, default='', max_length=64)),
                ('rock', models.CharField(blank=True, default='', max_length=64)),
                ('U_start', models.CharField(blank=True, default='', max_length=64)),
                ('U_stop', models.CharField(blank=True, default='', max_length=64)),
                ('data_center', models.CharField(blank=True, default='', max_length=64)),
                ('vendors', models.CharField(blank=True, default='', max_length=128)),
                ('cluster', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'resource_host_2_zabbix',
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('status', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings', to='dashBoard.DeviceGroup')),
            ],
            options={
                'db_table': 'routing',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('Vendor', models.IntegerField(null=True)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('agent', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('DeviceLev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='dashBoard.DeviceLev')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='dashBoard.DeviceGroup')),
            ],
            options={
                'db_table': 'server',
            },
        ),
        migrations.CreateModel(
            name='ServerToZabbix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('host_ip', models.CharField(blank=True, default='', max_length=64)),
                ('app_name', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.CharField(blank=True, default='', max_length=64)),
                ('park', models.CharField(blank=True, default='', max_length=64)),
                ('room', models.CharField(blank=True, default='', max_length=64)),
                ('rock', models.CharField(blank=True, default='', max_length=64)),
                ('U_start', models.CharField(blank=True, default='', max_length=64)),
                ('U_stop', models.CharField(blank=True, default='', max_length=64)),
                ('data_center', models.CharField(blank=True, default='', max_length=64)),
                ('vendors', models.CharField(blank=True, default='', max_length=128)),
                ('cluster', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'server_2_zabbix',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('ip', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('agent', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storages', to='dashBoard.DeviceGroup')),
            ],
            options={
                'db_table': 'storage',
            },
        ),
        migrations.CreateModel(
            name='StorageToZabbix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('host_ip', models.CharField(blank=True, default='', max_length=64)),
                ('app_name', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.CharField(blank=True, default='', max_length=64)),
                ('park', models.CharField(blank=True, default='', max_length=64)),
                ('room', models.CharField(blank=True, default='', max_length=64)),
                ('rock', models.CharField(blank=True, default='', max_length=64)),
                ('U_start', models.CharField(blank=True, default='', max_length=64)),
                ('U_stop', models.CharField(blank=True, default='', max_length=64)),
                ('data_center', models.CharField(blank=True, default='', max_length=64)),
                ('vendors', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'storage_2_zabbix',
            },
        ),
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('status', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='dashBoard.DeviceGroup')),
            ],
            options={
                'db_table': 'switches',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=128)),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ZabbixPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=512)),
                ('zabbix_id', models.IntegerField()),
                ('url', models.CharField(max_length=126)),
            ],
            options={
                'db_table': 'zabbix_pass',
            },
        ),
        migrations.AddField(
            model_name='switches',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='dashBoard.User'),
        ),
        migrations.AddField(
            model_name='storage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storages', to='dashBoard.User'),
        ),
        migrations.AddField(
            model_name='server',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='dashBoard.User'),
        ),
        migrations.AddField(
            model_name='routing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings', to='dashBoard.User'),
        ),
        migrations.AddField(
            model_name='resourcehost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_hosts', to='dashBoard.User'),
        ),
        migrations.AddField(
            model_name='fz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fzs', to='dashBoard.User'),
        ),
        migrations.AddField(
            model_name='fw',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fws', to='dashBoard.User'),
        ),
        migrations.AddField(
            model_name='clouddevice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_devices', to='dashBoard.DeviceGroup'),
        ),
        migrations.AddField(
            model_name='clouddevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_devices', to='dashBoard.User'),
        ),
        migrations.AddField(
            model_name='alerthis',
            name='lev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_hiss', to='dashBoard.AlertLev'),
        ),
        migrations.AddField(
            model_name='alert',
            name='lev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='dashBoard.AlertLev'),
        ),
    ]
